# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e44284d1eb8149ac3f3f41bb703acb4d0eb0ff15beb5828c4514d10bd4ae2c70cc0c11b923e769869ce158946e9f299cdca87777bf9a03184ae3c1025c64d580

test:
  secret_key_base: faad68b5923d3e0382ed978dbfe88035219396b8341e4a3150be057bf2adb05727c361d0ffb5db2492f9d08afa7a38e2b3350cdb41659979683a0b8356551446

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
