mailer:
  from: "notice@offkara.jp"

  event:
    from: "event-notice@offkara.jp"

    participation_application_completed_notify:
      subject: "OFF KARA | イベントへの参加申請が完了しました！"

    notify_result_of_lottery_to_winners:
      subject: "OFF KARA | 当選のお知らせ"

    notify_result_of_lottery_to_rejected_people:
      subject: "OFF KARA | 落選のお知らせ"

    event_holding_reminder:
      subject: "OFF KARA | オフ会イベント前日リマインド"
